# Cambiar el puerto si lo deseas (por defecto es 8080)
server.port=8080

# Exponer los puntos de acceso de Actuator y Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=servicio-web-evaluacion